language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=etltest setup.py test"
    - 'tox'
before_script:
  - mysql -e 'create database etlUnitTest;'
  - mysql -e 'source scripts/etlUnitTest_build.sql'
services:  mysql
env: ETL_TEST_ROOT=/home/travis/build/OpenDataAlex/etlTest/
after_success:
    coveralls
